#!/bin/bash -e

# cleanup
rm -r /home/k/sharding/a/* /home/k/sharding/b/* /home/k/sharding/config/*


/home/k/gitroot/p/mongod --dbpath ~/sharding/a --port 10000 > ~/sharding/logs/sharda.log &
echo "started shard a"

/home/k/gitroot/p/mongod --dbpath ~/sharding/b --port 10001 > ~/sharding/logs/shardb.log &
echo "started shard b"

/home/k/gitroot/p/mongod --dbpath ~/sharding/config --port 20000 > ~/sharding/logs/configdb.log &
echo "started config"

sleep 3

/home/k/gitroot/p/mongos --configdb localhost:20000 > ~/sharding/logs/mongos.log &
echo "started mongos"
